{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/error"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"sections":[],"metadata":{"title":"error","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6OpenAI8APIErrorV","kind":"typeIdentifier","text":"APIError"}],"symbolKind":"property","role":"symbol","externalID":"s:6OpenAI16APIErrorResponseV5errorAA0C0Vvp","modules":[{"name":"OpenAI"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6OpenAI8APIErrorV","text":"APIError","kind":"typeIdentifier","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"}],"platforms":["macOS"]}]}],"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error","interfaceLanguage":"swift"},"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/error":{"abstract":[],"type":"topic","url":"\/documentation\/openai\/apierrorresponse\/error","title":"error","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6OpenAI8APIErrorV","kind":"typeIdentifier","text":"APIError"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","title":"OpenAI","url":"\/documentation\/openai","kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"abstract":[],"type":"topic","url":"\/documentation\/openai\/apierror","title":"APIError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","navigatorTitle":[{"kind":"identifier","text":"APIError"}]},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","title":"APIErrorResponse","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"APIErrorResponse"}],"url":"\/documentation\/openai\/apierrorresponse","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIErrorResponse","kind":"identifier"}]}}}