{"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"APIError","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","kind":"typeIdentifier","preciseIdentifier":"s:6OpenAI8APIErrorV"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:6OpenAI16APIErrorResponseV5errorAA0C0Vvp","modules":[{"name":"OpenAI"}],"roleHeading":"Instance Property","symbolKind":"property","title":"error","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"APIError","preciseIdentifier":"s:6OpenAI8APIErrorV"}]},"variants":[{"paths":["\/documentation\/openai\/apierrorresponse\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/error":{"abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6OpenAI8APIErrorV","text":"APIError","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error","role":"symbol","url":"\/documentation\/openai\/apierrorresponse\/error","kind":"symbol","title":"error"},"doc://OpenAI/documentation/OpenAI":{"url":"\/documentation\/openai","title":"OpenAI","role":"collection","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol","abstract":[],"type":"topic"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","title":"APIErrorResponse","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIErrorResponse"}],"navigatorTitle":[{"text":"APIErrorResponse","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openai\/apierrorresponse"},"doc://OpenAI/documentation/OpenAI/APIError":{"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"url":"\/documentation\/openai\/apierror","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"APIError","kind":"identifier"}],"title":"APIError","type":"topic"}}}