{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"metadata":{"symbolKind":"property","title":"errorDescription","roleHeading":"Instance Property","modules":[{"name":"OpenAI"}],"extendedModule":"OpenAI","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"externalID":"s:6OpenAI8APIErrorV16errorDescriptionSSSgvp"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/errordescription"]}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"]]},"kind":"symbol","references":{"doc://OpenAI/documentation/OpenAI/APIError/LocalizedError-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/openai\/apierror\/localizederror-implementations","kind":"article","role":"collectionGroup","title":"LocalizedError Implementations","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"doc://OpenAI/documentation/OpenAI":{"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","title":"OpenAI","type":"topic","abstract":[],"url":"\/documentation\/openai","role":"collection"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"url":"\/documentation\/openai\/apierror\/errordescription","kind":"symbol","type":"topic","title":"errorDescription","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","url":"\/documentation\/openai\/apierror","title":"APIError","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"navigatorTitle":[{"text":"APIError","kind":"identifier"}]}}}