{"kind":"article","metadata":{"modules":[{"name":"OpenAI"}],"role":"collectionGroup","roleHeading":"API Collection","title":"LocalizedError Implementations"},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"variants":[{"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"APIError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","title":"APIError","url":"\/documentation\/openai\/apierror","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://OpenAI/documentation/OpenAI":{"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","url":"\/documentation\/openai","kind":"symbol","type":"topic","title":"OpenAI","role":"collection"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","title":"recoverySuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/openai\/apierror\/recoverysuggestion"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/openai\/apierror\/errordescription","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"title":"failureReason","role":"symbol","url":"\/documentation\/openai\/apierror\/failurereason"},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/openai\/apierror\/helpanchor","title":"helpAnchor","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]}}}