{"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"topicSections":[{"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"generated":true,"title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"collectionGroup","modules":[{"name":"OpenAI"}],"title":"LocalizedError Implementations","roleHeading":"API Collection"},"sections":[],"kind":"article","references":{"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","abstract":[],"url":"\/documentation\/openai\/apierror\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","title":"helpAnchor","kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"url":"\/documentation\/openai\/apierror\/recoverysuggestion","role":"symbol","title":"recoverySuggestion","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError":{"url":"\/documentation\/openai\/apierror","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"APIError","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}]},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"type":"topic","url":"\/documentation\/openai\/apierror\/errordescription","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","abstract":[],"title":"errorDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"type":"topic","url":"\/documentation\/openai\/apierror\/failurereason","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","abstract":[],"title":"failureReason","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI":{"title":"OpenAI","url":"\/documentation\/openai","kind":"symbol","role":"collection","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","type":"topic","abstract":[]}}}