{"variants":[{"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"metadata":{"modules":[{"name":"OpenAI"}],"role":"collectionGroup","roleHeading":"API Collection","title":"LocalizedError Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"kind":"article","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"generated":true}],"references":{"doc://OpenAI/documentation/OpenAI":{"url":"\/documentation\/openai","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","abstract":[],"type":"topic","role":"collection","kind":"symbol","title":"OpenAI"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"abstract":[],"kind":"symbol","type":"topic","title":"errorDescription","url":"\/documentation\/openai\/apierror\/errordescription","role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"url":"\/documentation\/openai\/apierror\/helpanchor","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"helpAnchor","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","type":"topic","kind":"symbol","role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APIError"}],"url":"\/documentation\/openai\/apierror","title":"APIError","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"APIError"}],"type":"topic","kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"title":"recoverySuggestion","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/openai\/apierror\/recoverysuggestion","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","role":"symbol","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"failureReason","abstract":[],"url":"\/documentation\/openai\/apierror\/failurereason"}}}